workflows:
  ios_release_build:
    name: iOS Release Build
    environment:
      flutter: "3.29.2"
      xcode: latest
      groups:
        - env
      vars:
        P12_PASSWORD: $P12_PASSWORD
        CERTIFICATE_URL: $CERTIFICATE_URL
        PROVISIONING_PROFILE_URL: $PROVISIONING_PROFILE_URL
        SUPABASE_URL: $SUPABASE_URL
        SUPABASE_ANON_KEY: $SUPABASE_ANON_KEY
        ADMOB_BANNER_ID_ANDROID: $ADMOB_BANNER_ID_ANDROID
        ADMOB_BANNER_ID_IOS: $ADMOB_BANNER_ID_IOS
        ADMOB_REWARDED_ID_ANDROID: $ADMOB_REWARDED_ID_ANDROID
        ADMOB_REWARDED_ID_IOS: $ADMOB_REWARDED_ID_IOS
        BUNDLE_ID: com.zlabo.wonmoremoneybook  # ðŸ‘ˆ ì—¬ê¸° ë„ˆ ì•± ë²ˆë“¤ ì•„ì´ë”” ë„£ì–´

    scripts:
      - name: ðŸ” Decode and install signing files
        script: |
          echo $CERTIFICATE_URL | base64 --decode > signing.p12
          echo $PROVISIONING_PROFILE_URL | base64 --decode > profile.mobileprovision
          
          echo "âœ… Profile file size: $(ls -la profile.mobileprovision)"
          echo "âœ… Profile content preview:"
          head -5 profile.mobileprovision
    
    
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          uuid=$(grep -a -o 'UUID.*</string>' profile.mobileprovision | head -1 | sed -e 's/.*<string>\(.*\)<\/string>/\1/')
          profile_name=$(grep -a -A1 '<key>Name</key>' profile.mobileprovision | tail -1 | sed -e 's/.*<string>\(.*\)<\/string>/\1/')
          
          echo "âœ… Extracted UUID: $uuid"
          echo "âœ… Extracted Provisioning Profile Name: $profile_name"
          
          cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/$uuid.mobileprovision
          
          echo "âœ… Installed profiles:"
          ls -la ~/Library/MobileDevice/Provisioning\ Profiles/

          security create-keychain -p "" build.keychain
          security import signing.p12 -k build.keychain -P "$P12_PASSWORD" -T /usr/bin/codesign
          security list-keychains -s build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain

      - name: ðŸ§¾ Generate ExportOptions.plist
        script: |
          echo "âœ… ExportOptions.plist will use profile name: $profile_name"

          echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" > ExportOptions.plist
          echo "<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">" >> ExportOptions.plist
          echo "<plist version=\"1.0\">" >> ExportOptions.plist
          echo "<dict>" >> ExportOptions.plist
          echo "  <key>method</key>" >> ExportOptions.plist
          echo "  <string>app-store</string>" >> ExportOptions.plist
          echo "  <key>signingStyle</key>" >> ExportOptions.plist
          echo "  <string>manual</string>" >> ExportOptions.plist
          echo "  <key>provisioningProfiles</key>" >> ExportOptions.plist
          echo "  <dict>" >> ExportOptions.plist
          echo "    <key>${BUNDLE_ID}</key>" >> ExportOptions.plist
          echo "    <string>${profile_name}</string>" >> ExportOptions.plist
          echo "  </dict>" >> ExportOptions.plist
          echo "  <key>compileBitcode</key>" >> ExportOptions.plist
          echo "  <false/>" >> ExportOptions.plist
          echo "  <key>destination</key>" >> ExportOptions.plist
          echo "  <string>export</string>" >> ExportOptions.plist
          echo "</dict>" >> ExportOptions.plist
          echo "</plist>" >> ExportOptions.plist
      

      - name: ðŸ§ª Generate .env file
        script: |
          echo "SUPABASE_URL=$SUPABASE_URL" >> .env
          echo "SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY" >> .env
          echo "ADMOB_BANNER_ID_ANDROID=$ADMOB_BANNER_ID_ANDROID" >> .env
          echo "ADMOB_BANNER_ID_IOS=$ADMOB_BANNER_ID_IOS" >> .env
          echo "ADMOB_REWARDED_ID_ANDROID=$ADMOB_REWARDED_ID_ANDROID" >> .env
          echo "ADMOB_REWARDED_ID_IOS=$ADMOB_REWARDED_ID_IOS" >> .env

      - name: ðŸ“¦ Install dependencies
        script: flutter pub get

      - name: ðŸš€ Build iOS release
        script: flutter build ipa --release --export-options-plist=ExportOptions.plist

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        apple_id: shincw1142@gmail.com
        password: $APP_SPECIFIC_PASSWORD
