workflows:
  ios_release_build:
    name: iOS Release Build
    environment:
      flutter: "3.29.2"
      xcode: latest
      vars:
        SUPABASE_URL: $SUPABASE_URL
        SUPABASE_ANON_KEY: $SUPABASE_ANON_KEY
        ADMOB_BANNER_ID_ANDROID: $ADMOB_BANNER_ID_ANDROID
        ADMOB_BANNER_ID_IOS: $ADMOB_BANNER_ID_IOS
        ADMOB_REWARDED_ID_ANDROID: $ADMOB_REWARDED_ID_ANDROID
        ADMOB_REWARDED_ID_IOS: $ADMOB_REWARDED_ID_IOS
        P12_PASSWORD: $P12_PASSWORD
        CERTIFICATE_URL: $CERTIFICATE_URL
        PROVISIONING_PROFILE_URL: $PROVISIONING_PROFILE_URL
    scripts:
      - name: Generate .env file
        script: |
          echo "SUPABASE_URL=$SUPABASE_URL" >> .env
          echo "SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY" >> .env
          echo "ADMOB_BANNER_ID_ANDROID=$ADMOB_BANNER_ID_ANDROID" >> .env
          echo "ADMOB_BANNER_ID_IOS=$ADMOB_BANNER_ID_IOS" >> .env
          echo "ADMOB_REWARDED_ID_ANDROID=$ADMOB_REWARDED_ID_ANDROID" >> .env
          echo "ADMOB_REWARDED_ID_IOS=$ADMOB_REWARDED_ID_IOS" >> .env

      - name: Install dependencies
        script: flutter pub get

      - name: Build iOS release
        script: flutter build ios --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        apple_id: shincw1142@gmail.com
        password: $APP_SPECIFIC_PASSWORD
