workflows:
  ios_release_build:
    name: iOS Release Build
    environment:
      flutter: "3.29.2"
      xcode: latest
      groups:
        - env
      vars:
        P12_PASSWORD: $P12_PASSWORD
        CERTIFICATE_URL: $CERTIFICATE_URL
        PROVISIONING_PROFILE_URL: $PROVISIONING_PROFILE_URL
        SUPABASE_URL: $SUPABASE_URL
        SUPABASE_ANON_KEY: $SUPABASE_ANON_KEY
        ADMOB_BANNER_ID_ANDROID: $ADMOB_BANNER_ID_ANDROID
        ADMOB_BANNER_ID_IOS: $ADMOB_BANNER_ID_IOS
        ADMOB_REWARDED_ID_ANDROID: $ADMOB_REWARDED_ID_ANDROID
        ADMOB_REWARDED_ID_IOS: $ADMOB_REWARDED_ID_IOS
        BUNDLE_ID: com.zlabo.wonmoremoneybook

    scripts:
      - name: ðŸ” Decode and install signing files
        script: |
          echo "ðŸ” Debug - CERTIFICATE_URL length: ${#CERTIFICATE_URL}"
          echo "ðŸ” Debug - PROVISIONING_PROFILE_URL length: ${#PROVISIONING_PROFILE_URL}"
          
          echo $CERTIFICATE_URL | base64 --decode > signing.p12
          echo $PROVISIONING_PROFILE_URL | base64 --decode > profile.mobileprovision

          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          uuid=$(grep -a -o 'UUID.*</string>' profile.mobileprovision | head -1 | sed -e 's/.*<string>\(.*\)<\/string>/\1/')
          profile_name=$(grep -a -A1 '<key>Name</key>' profile.mobileprovision | tail -1 | sed -e 's/.*<string>\(.*\)<\/string>/\1/')
          cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/$uuid.mobileprovision

          security create-keychain -p "" build.keychain
          security import signing.p12 -k build.keychain -P "$P12_PASSWORD" -T /usr/bin/codesign
          security list-keychains -s build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain

      - name: ðŸ§¾ Generate ExportOptions.plist
        script: |
          cat > ExportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>signingStyle</key>
            <string>manual</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>${BUNDLE_ID}</key>
              <string>${profile_name}</string>
            </dict>
            <key>compileBitcode</key>
            <false/>
            <key>destination</key>
            <string>export</string>
          </dict>
          </plist>
          EOF

      - name: ðŸ§ª Generate .env file
        script: |
          echo "SUPABASE_URL=$SUPABASE_URL" >> .env
          echo "SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY" >> .env
          echo "ADMOB_BANNER_ID_ANDROID=$ADMOB_BANNER_ID_ANDROID" >> .env
          echo "ADMOB_BANNER_ID_IOS=$ADMOB_BANNER_ID_IOS" >> .env
          echo "ADMOB_REWARDED_ID_ANDROID=$ADMOB_REWARDED_ID_ANDROID" >> .env
          echo "ADMOB_REWARDED_ID_IOS=$ADMOB_REWARDED_ID_IOS" >> .env

      - name: ðŸ“¦ Install dependencies
        script: flutter pub get

      - name: ðŸš€ Build iOS release
        script: flutter build ipa --release --export-options-plist=ExportOptions.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.dSYM.zip
      - ExportOptions.plist
      - .env

    publishing:
      app_store_connect:
        apple_id: shincw1142@gmail.com
        password: $APP_SPECIFIC_PASSWORD
