workflows:
  ios_release_build:
    name: iOS Release Build
    environment:
      flutter: "3.29.2"
      xcode: latest
      vars:
        SUPABASE_URL: $SUPABASE_URL
        SUPABASE_ANON_KEY: $SUPABASE_ANON_KEY
        ADMOB_BANNER_ID_ANDROID: $ADMOB_BANNER_ID_ANDROID
        ADMOB_BANNER_ID_IOS: $ADMOB_BANNER_ID_IOS
        ADMOB_REWARDED_ID_ANDROID: $ADMOB_REWARDED_ID_ANDROID
        ADMOB_REWARDED_ID_IOS: $ADMOB_REWARDED_ID_IOS
        P12_PASSWORD: $P12_PASSWORD
        CERTIFICATE_URL: $CERTIFICATE_URL
        PROVISIONING_PROFILE_URL: $PROVISIONING_PROFILE_URL
    scripts:
      - name: Generate .env file
        script: |
          echo "SUPABASE_URL=$SUPABASE_URL" >> .env
          echo "SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY" >> .env
          echo "ADMOB_BANNER_ID_ANDROID=$ADMOB_BANNER_ID_ANDROID" >> .env
          echo "ADMOB_BANNER_ID_IOS=$ADMOB_BANNER_ID_IOS" >> .env
          echo "ADMOB_REWARDED_ID_ANDROID=$ADMOB_REWARDED_ID_ANDROID" >> .env
          echo "ADMOB_REWARDED_ID_IOS=$ADMOB_REWARDED_ID_IOS" >> .env

      - name: Install dependencies
        script: flutter pub get

      - name: Build iOS release
        script: flutter build ios --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa

    code_signing:
      certificate: wonmore_money_book_appstore_cert
      certificate_password: $P12_PASSWORD
      provisioning_profiles: wonmore_money_book_appstore_profile
      bundle_identifier: com.zlabo.wonmoremoneybook

    publishing:
      app_store_connect:
        apple_id: shincw1142@gmail.com  # ✅ 애플 로그인 이메일
        password: $APP_SPECIFIC_PASSWORD        # ✅ 앱 전용 비밀번호 (환경변수 등록 필수)
