workflows:
  ios_release_build:
    name: iOS Release Build
    environment:
      flutter: "3.29.2"  # 너가 사용하는 버전 확인 후 맞춰줘
      xcode: latest
      vars:
        BUNDLE_ID: com.zlabo.wonmoremoneybook
      groups:
        - app_store_credentials
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build iOS release
        script: |
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.dSYM.zip
      - build/ios/ipa/*.app.zip
    publishing:
      app_store_connect:
        credentials: app_store_credentials
        app_store_id: 6749498023  # ⚠️ App Store에 등록된 앱의 ID 숫자
        bundle_id: $BUNDLE_ID
        submit_to_testflight: false
        submit_to_app_store: true

groups:
  app_store_credentials:
    environment:
      APP_STORE_CONNECT_ISSUER_ID: 70d8afd8-b6bb-4c5e-b4a2-6d400ab0c97c
      APP_STORE_CONNECT_KEY_IDENTIFIER: MMUNJ7YMJF
      APP_STORE_CONNECT_PRIVATE_KEY: |
        -----BEGIN PRIVATE KEY-----
        MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgSUQpIQ+zaiegwalS
        b+XW5DlhIcYlhyVnFcTe1KOIDFegCgYIKoZIzj0DAQehRANCAAQj9dQ8qYI6m4yh
        avF75Er96OgnNDb27ZN86szFpOI9f+Rx+Y0aWC9Jpq3IW+MrzwklVG/8Ja04In6M
        B7LCJH9W
        -----END PRIVATE KEY-----
