workflows:
  ios_release_build:
    name: iOS Release Build
    environment:
      flutter: "3.29.2"
      xcode: latest
      groups:
        - env  # Codemagic ì›¹ì—ì„œ ë§Œë“  env ê·¸ë£¹

    scripts:
      - name: ðŸ§ª Generate .env file
        script: |
          echo "SUPABASE_URL=$SUPABASE_URL" >> .env
          echo "SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY" >> .env
          echo "ADMOB_BANNER_ID_ANDROID=$ADMOB_BANNER_ID_ANDROID" >> .env
          echo "ADMOB_BANNER_ID_IOS=$ADMOB_BANNER_ID_IOS" >> .env
          echo "ADMOB_REWARDED_ID_ANDROID=$ADMOB_REWARDED_ID_ANDROID" >> .env
          echo "ADMOB_REWARDED_ID_IOS=$ADMOB_REWARDED_ID_IOS" >> .env

      - name: ðŸ“¦ Install dependencies
        script: flutter pub get

      - name: ðŸš€ Build iOS release
        script: flutter build ipa --release

    code_signing:
      automatic_code_signing:
        team_id: $TEAM_ID
        bundle_identifier: $BUNDLE_ID

    artifacts:
      - build/ios/ipa/*.ipa
