workflows:
  ios_release:
    name: iOS Release (Flutter + verbose upload)
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      flutter: 3.29.2
      xcode: 16.4
      cocoapods: default
      vars:
        # 네 앱 번들 ID (App Store Connect에 등록된 것과 동일)
        BUNDLE_ID: com.zlabo.wonmoremoneybook

    # ====== UI의 Pre-build script 반영 (.env 생성) ======
    scripts:
      - name: Pre-build (.env write)
        script: |
          set -euxo pipefail
          echo "SUPABASE_URL=$SUPABASE_URL" >> .env
          echo "SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY" >> .env
          echo "ADMOB_BANNER_ID_ANDROID=$ADMOB_BANNER_ID_ANDROID" >> .env
          echo "ADMOB_BANNER_ID_IOS=$ADMOB_BANNER_ID_IOS" >> .env
          echo "ADMOB_REWARDED_ID_ANDROID=$ADMOB_REWARDED_ID_ANDROID" >> .env
          echo "ADMOB_REWARDED_ID_IOS=$ADMOB_REWARDED_ID_IOS" >> .env

      # ====== iOS 코드서명(자동) — UI의 Automatic과 동일 동작 ======
      - name: Prepare iOS code signing (automatic)
        script: |
          set -euxo pipefail
          # App Store용 서명파일 자동 생성/조회
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
          # 키체인에 인증서 설치
          keychain add-certificates
          # Xcode 프로젝트에 프로파일 적용 + export_options.plist 생성
          xcode-project use-profiles

      # ====== Flutter로 정상 IPA 생성 (Runner.app 포함) ======
      - name: Flutter build IPA (Release)
        script: |
          set -euxo pipefail
          flutter clean
          flutter pub get
          : "${BUILD_NUMBER:=1}"
          # xcode-project use-profiles가 만든 export_options.plist 사용
          # (일반적으로 $HOME/export_options.plist, 환경에 따라 /Users/builder/export_options.plist 에 생성)
          EXPORT_PLIST="${HOME}/export_options.plist"
          [ -f "$EXPORT_PLIST" ] || EXPORT_PLIST="/Users/builder/export_options.plist"
          flutter build ipa --release \
            --build-number="$BUILD_NUMBER" \
            --export-options-plist "$EXPORT_PLIST"

      # ====== UI의 Post‑publish script 반영(IPA 검사 + --verbose 업로드) ======
      - name: Publish to App Store Connect (verbose)
        script: |
          #!/usr/bin/env bash
          set -euxo pipefail

          # ==== 0) 필수 환경변수 검증 ====
          : "${APP_STORE_CONNECT_KEY_ID:?Set APP_STORE_CONNECT_KEY_ID in Environment variables}"
          : "${APP_STORE_CONNECT_ISSUER_ID:?Set APP_STORE_CONNECT_ISSUER_ID in Environment variables}"
          : "${APP_STORE_CONNECT_PUBLISHER_PRIVATE_KEY:?Set APP_STORE_CONNECT_PUBLISHER_PRIVATE_KEY (multiline)}"

          # ==== 1) IPA 위치 자동 탐색 ====
          CANDIDATES=()
          [ -n "${CM_EXPORT_DIR:-}" ] && CANDIDATES+=("$CM_EXPORT_DIR/App.ipa")
          [ -n "${CM_BUILD_DIR:-}" ] && CANDIDATES+=("$CM_BUILD_DIR/build/ios/ipa/App.ipa")
          CANDIDATES+=("/Users/builder/clone/build/ios/ipa/App.ipa")

          IPA=""
          for p in "${CANDIDATES[@]}"; do
            [ -f "$p" ] && IPA="$p" && break
          done
          [ -z "$IPA" ] && IPA="$(/usr/bin/find /Users/builder -type f -name '*.ipa' -print -quit || true)"

          [ -n "$IPA" ] && [ -f "$IPA" ] || { echo "❌ IPA not found. Checked: ${CANDIDATES[*]}"; exit 1; }
          echo "✅ Found IPA at: $IPA"

          # ==== 2) 앱 Info.plist 확인(.app 한정) ====
          TMP_DIR="$(mktemp -d)"
          unzip -q "$IPA" -d "$TMP_DIR"
          PLIST="$(find "$TMP_DIR/Payload" -type f -path '*/.app/Info.plist' | head -1 || true)"
          if [ -n "$PLIST" ]; then
            echo "ℹ️ From App .app/Info.plist:"
            /usr/libexec/PlistBuddy -c 'Print :CFBundleIdentifier' "$PLIST" || true
            /usr/libexec/PlistBuddy -c 'Print :CFBundleShortVersionString' "$PLIST" || true
            /usr/libexec/PlistBuddy -c 'Print :CFBundleVersion' "$PLIST" || true
          else
            echo "⚠️ App .app/Info.plist not found (framework plist was ignored)."
          fi

          # ==== 3) --verbose로 업로드 ====
          app-store-connect publish \
            --path "$IPA" \
            --key-id "$APP_STORE_CONNECT_KEY_ID" \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --private-key @env:APP_STORE_CONNECT_PUBLISHER_PRIVATE_KEY \
            --verbose

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.dSYM.zip

    # (중복 업로드 방지용) 기본 퍼블리셔는 끄기
    publishing:
      app_store_connect:
        submit_to_testflight: false
        submit_to_app_store: false
