workflows:
  ios_release_build:
    name: iOS Release Build
    environment:
      flutter: "3.29.2"
      xcode: latest
      groups:
        - env  # Codemagic 웹에서 관리하는 환경변수 그룹
    scripts:
      - name: 🧪 Generate .env file
        script: |
          echo "SUPABASE_URL=$SUPABASE_URL" >> .env
          echo "SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY" >> .env
          echo "ADMOB_BANNER_ID_ANDROID=$ADMOB_BANNER_ID_ANDROID" >> .env
          echo "ADMOB_BANNER_ID_IOS=$ADMOB_BANNER_ID_IOS" >> .env
          echo "ADMOB_REWARDED_ID_ANDROID=$ADMOB_REWARDED_ID_ANDROID" >> .env
          echo "ADMOB_REWARDED_ID_IOS=$ADMOB_REWARDED_ID_IOS" >> .env

      - name: 📦 Install dependencies
        script: flutter pub get

      - name: 🚀 Build iOS release
        script: flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa
