name: wonmore_money_book
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.7+14

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  drift: ^2.14.1
  sqlite3_flutter_libs: ^0.5.18
  path_provider: ^2.1.2
  path: ^1.8.3
  supabase_flutter: ^2.3.4
  table_calendar: ^3.0.9
  provider: ^6.1.1
  intl: ^0.19.0
  shared_preferences: ^2.5.3
  another_flushbar: ^1.12.30
  google_mobile_ads: ^6.0.0
  month_picker_dialog: ^6.0.3
  fl_chart: ^1.0.0
  google_sign_in: ^6.3.0
  connectivity_plus: ^6.1.4
  uuid: ^4.5.1
  http: ^1.4.0
  image_picker: ^1.1.2
  share_plus: ^11.0.0
  sign_in_with_apple: ^7.0.1
  flutter_dotenv: ^5.2.1
  url_launcher: ^6.3.2
  change_app_package_name: ^1.5.0
  tutorial_coach_mark: ^1.3.1
  in_app_purchase: ^3.2.3
  firebase_core: ^4.1.0
  firebase_messaging: ^16.0.1
  flutter_local_notifications: ^19.4.1
  in_app_purchase_android: ^0.4.0+4
  excel: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.14.1
  build_runner: ^2.4.8
  flutter_native_splash: ^2.3.5

flutter_native_splash:
  color: "#A982F1"  # 밝은 보라색 배경
  image: assets/img/splash_icon.png # 원하면 코인 아이콘 썸네일도 가능
  android_gravity: center

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/g-logo.png
    - assets/img/kakao_bubble.png
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansKR-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansKR-Bold.ttf
          weight: 600

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
